apiVersion: apps/v1
kind: Deployment
metadata:
  name: sns-api
  namespace: {{ .Values.namespace }}
  labels:
    revision: {{ .Values.revision }}
  spec:
    replicas: {{ .Values.replicas }}
    template:
      metadata:
        labels:
          name: sns-api
          version: {{ .Values.color }}
          namespace: {{ .Values.namespace }}
          revision: {{ .Values.revision }}
      spec:
        containers:
          - name: sns-api
            image: sns-api
            imagePullPolicy: Always
            ports:
              - containerPort: 8080
            resources:
              requests:
                memory: {{ .Values.resources.requests.memory }}
  selector:
    matchLabels:
      name: sns-api
      version: {{ .Values.color }}