apiVersion: v1
kind: Service
metadata:
  name: sns-api-svc
  namespace: {{ .Values.namespace }}
  labels:
    revision: {{ .Values.revision }}
spec:
  type: NodePort
  ports:
    - port: 15000
      protocol: TCP
      targetPort: 8081
  selector:
    name: sns-api