apiVersion: v1
metadata:
  name: sns-db-svc
  namespace: {{ .Values.namespace }}
  labels:
    revision: {{ .Values.revision }}
kind: Service
spec:
  ports:
    - name: sns-db-svc
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: NodePort
  selector:
    name: sns-db
